### ISSUE TITLE
Support queries without rrname or rdata

### ISSUE THREAD

**Issue by King-Konsto** [DCSO/balboa#22]
I would like to get all TXT records for a specific sensor:
```GraphQL
 query { 
  e1:entries(rrtype:TXT, sensor_id:"<sensor_id>")
		{
			rrname 
                        rrtype
			rdata 
			sensor_id
			time_first_rfc3339 
			time_last_rfc3339
			count 
   },
}
```
This query leads to: at least one of the 'rdata' or 'rrname' parameters is required"
To reduce the length of the output it would also be great to have the possibility to limit the number of results returned.

**Comment by satta** [comment]
I think that for that kind of bulk query (i.e. without a proper search term) the GraphQL interface is not very suitable, even if there's a way to limit the results. If there are hundreds of thousands of results, what good would a limit for the first 1000 be? Or even if it's 10000... the problem would still be the same, one would need to send a lot of data over to the client.

I think one would either need proper pagination (limit _and_ offset -- but that would also require some kind of stateful resut object to avoid reporting changing states of data while fetching each chunk) or some kind of export/dump functionality that bypasses GraphQL for a more suitable delivery method.
What do you think?

**Comment by King-Konsto** [comment]
I think you are right. Maybe we can add this function also to #18 to get a database dump for only one rrtype and one sensor_id?

**Comment by satta** [comment]
I recommend to simply dump the database and filter via `jq` for a given value of `sensor_id`.
