### ISSUE TITLE
LZ4 not linked with Rocksdb binary

### ISSUE THREAD

**Issue by gallypette** [DCSO/balboa#38]
Hi,

I encounter an error while trying to launch Rocksdb under Ubuntu 18.04 (make goes ok):

``` shell
<3> (blb_rocksdb_open) rocksdb_open() failed: `Invalid argument: Compression type LZ4 is not linked with the binary.`
```
So I added liblz4-dev, make clean, make, but still no joy.
Any idea?
cheers.

**Comment by satta** [comment]
Looks like this is an issue with Ubuntu bionic's rocksdb package. It seems they didn't compile it with LZ4 support.
I can see from https://packages.ubuntu.com/source/cosmic/rocksdb that the librocksdb from the next version Ubuntu cosmic (18.10) seems to be linked against liblz4, so if there is an option to use that version, this is what I would suggest.

**Comment by gallypette** [comment]
Ok, i will try this way then--thanks.
