### ISSUE TITLE
Balboa binary not produced

### ISSUE THREAD

**Issue by gallypette** [DCSO/balboa#39]
Ubuntu 18.04 / 18.10
Go 1.12

```
$ go get github.com/DCSO/balboa
can't load package: package github.com/DCSO/balboa: no Go files in /home/jlouis/go/src/github.com/DCSO/balboa
```

**Comment by satta** [comment]
Ah, thanks for spotting this. If you want to `go get` this, you will need to do:
```
$ go get github.com/DCSO/balboa/cmd/balboa
```
I have also raised a PR fixing this in master: https://github.com/DCSO/balboa/pull/40

**Comment by gallypette** [comment]
All good thanks.
